name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build --file Dockerfile --tag ${DOCKER_ORGANIZATION_NAME}/${DOCKER_IMAGE_NAME}:latest .
        env:
          DOCKER_ORGANIZATION_NAME: ${{ secrets.DOCKER_ORGANIZATION_NAME }}
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
